---
- hosts: 172.31.44.9
  become: yes
  tasks:
   - name: i want to execute command directly
     command: hostname -f
     register: myresult
   - name: i want to debug
     debug:
      msg: "{{myresult}}"