---
- hosts: 172.31.44.9
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: i want to install webserver
    apt:
     name: apache2
     state: present
  - name: i wanto copy index file into nodes
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
  
    


  