---
- hosts: mywebserver
  become: yes
  tasks:
    - name: i want to install webserver on ubuntu
      apt:
         name: 
         state: present
      when: ansible_os_family =="Debian"
    - name: i want to start webserver on ubuntu
      service:
         name:"{{mywebserveronubuntu}}"
         state:started
      when: ansible_os_family =="Debian"
    - name: i want to install webserver on redhat
      yum: 
         name: "{{mywebserveronredhat}}"
         state: present
      when:  ansible_os_family =="RedHat"
    - name: i want to start webserver
      service:
        name: "{{mywebserveronredhat}}"
        state: started
      when:  ansible_os_family =="RedHat"



