---
- name: create tomcat folder
  file:
    path: /opt/tomcat
    state: directory
    
- name: download tar file
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.5/bin/apache-tomcat-8.5.5-fulldocs.tar.gz
    dest: /home/ubuntu/apache-tomcat-8.5.5-fulldocs.tar.gz
- name: extract tar file
  command:
    cmd: sudo tar xzvf apache-tomcat-8.5.5-fulldocs.tar.gz  -C /opt/tomcat --strip-components=1
    creates: /opt/tomcat/LICENSE

