---
# tasks file for mytomcat08role
- include_tasks: installjava.yml 
- include_tasks: createtomcatuser.yml 
- include_tasks: installtomcat.yml 
- include_tasks: updatepermission.yml 
- include_tasks: servicefile.yml 
- include_tasks: starttomcat.yml 
- include_tasks: tomcatwebmanagement.yml 
 


